[tool.poetry]
name = "repl_python3_Calculator"
version = "0.1.0"
description = ""
authors = ["DoniTrump <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
getkey = "^0.6.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
